version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: '3333'
      CACHE_HOST: "redis"
      CACHE_PORT: '6379'
    ports:
      - '3333:3333'
    image: nightlord189/tcp-pow-go/server:latest
    restart: 'no'
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '3333'
    image: nightlord189/tcp-pow-go/client:latest
    restart: 'no'
    depends_on:
      - server

  redis:
      image: redis:6.2.6-alpine
      ports:
        - '6379:6379'
